Apps/apptercihrobotu/urls.py
from django.urls import path
from .views import HomePageView
from . import views

app_name = 'apptercihrobotu'
urlpatterns = [
    path('', HomePageView.as_view(), name='home_tercihrobotu'),
    #path('tyt_hesaplama',views.tyt_hesaplama,name="tyt_hesaplama"),
    #path('Sonuc/',views.secim,name='sonuc_tercihrobotu'),
    #path('',views.AlanAzaltma,name='home_tercihrobotu'),
    path('sonuchesapla/',views.alanAzaltma,name='sonuchesapla'),
    #path('searchuni/',views.searchuni,name='searchuni'),
]

University/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('comments/', include('Apps.comments.urls')),
    path('universities/', include('Apps.universities.urls')),
    path('', include('Apps.users.urls')),
    path('apptercih/',include('Apps.apptercih.urls')),
    path('calendar/',include('Apps.calendars.urls')),
    path('blogs/',include('Apps.blogs.urls')),
    path('tercihrobotu/',include('Apps.apptercihrobotu.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Apps/apptercihrobotu/models.py
from django.db import models

# Create your models here.


class Lisans42020(models.Model):
   ProgramKodu = models.IntegerField()
   UniversiteAdi = models.TextField()
   FakulteAdi = models.TextField()
   BolumAdi = models.TextField()
   PuanTuru = models.TextField()
   GenelKontenjan = models.IntegerField(null=True, blank=True)
   Yerlesen = models.IntegerField(null=True, blank=True)
   EnKucukPuan = models.DecimalField(max_digits=10, decimal_places=4,null=True, blank=True)
   EnBuyukPuan = models.DecimalField(max_digits=10, decimal_places=4,null=True, blank=True)
   OBKontenjan = models.IntegerField(null=True, blank=True)
   OBYerlesen = models.IntegerField(null=True, blank=True)
   OBEnKucukPuan = models.DecimalField(max_digits=10, decimal_places=4,null=True, blank=True)
   OBEnBuyukPuan = models.DecimalField(max_digits=10, decimal_places=4,null=True, blank=True)


class OnLisans2020(models.Model):
   ProgramKodu = models.IntegerField()
   UniversiteAdi = models.TextField()
   FakulteAdi = models.TextField()
   BolumAdi = models.TextField()
   PuanTuru = models.TextField()
   GenelKontenjan = models.IntegerField(null=True, blank=True)
   Yerlesen = models.IntegerField(null=True, blank=True)
   EnKucukPuan = models.DecimalField(max_digits=10, decimal_places=4,null=True, blank=True)
   EnBuyukPuan = models.DecimalField(max_digits=10, decimal_places=4,null=True, blank=True)
   OBKontenjan = models.IntegerField(null=True, blank=True)
   OBYerlesen = models.IntegerField(null=True, blank=True)
   OBEnKucukPuan = models.DecimalField(max_digits=10, decimal_places=4,null=True, blank=True)
   OBEnBuyukPuan = models.DecimalField(max_digits=10, decimal_places=4,null=True, blank=True)

Apps/apptercihrobotu/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic import ListView
from .models import Lisans42020,OnLisans2020
from django.http import HttpResponse, JsonResponse
from django.core import serializers

# Create your views here.
class HomePageView(TemplateView):
    template_name = 'apptercihrobotu/home.html'

class LisansListView(ListView):
    model = Lisans42020
    paginate_by = 50
    template_name = 'apptercihrobotu/home.html'
    puandegeri= 1.111
    ordering = ['-EnKucukPuan']
    #Lisans42020.objects.filter().order_by('-EnKucukPuan')    #enkücük puanın clasını belirtmedim ?
    #Lisans42020.objects.filter(puandegeri > Lisans42020.EnKucukPuan).order_by('-EnKucukPuan')    #enkücük puanın clasını belirtmedim ?

class OnLisansListView(ListView):
    model = OnLisans2020
    paginate_by = 50
    template_name = 'apptercihrobotu/home.html'
    puandegeri= 1.111
    ordering = ['-EnKucukPuan']

# def secim(LisansTuru,PuanTuru,Puangirisi):
#     if(LisansTuru==2):
#         onlisanslist=OnLisansListView.objects.all()
#         onlisanslist=onlisanslist.filter(PuanTuru__exac=TYT)
#         context={object_list:onlisanslist}
#         return render()

#         #Onlisanslistview cagır

#     else if (LisansTuru==3):
#         if Puanturu==1:
#             PuanTuru="SAY"
#         else if Puanturu==2:
#             PuanTuru="SOZ"
#         else if Puanturu==3:
#             PuanTuru="EA"
#         else if Puanturu==4:
#             PuanTuru="DİL"
#         #lisanslistviewcagır
#         pass
#     #else alert secim yapmadınız uyarısı



# def index(request):
#     return render(request, 'users/index.html', {})

# def searchuni(request):
#     if request.is_ajax and  request.method == 'POST':
#         university = request.POST['university']
#         bolum = request.POST['bolum']
#         data = serializers.serialize('json', OnLisans2020.objects.all())

#         return JsonResponse({'onnn':data,}, status=200)
#     return JsonResponse({}, status=400)

def alanAzaltma(request):
    
    if request.method == 'POST':
        LisansTuru = request.POST['LisansTuru']
        PuanTuru = request.POST['PuanTuru']
        PuanGirisi =request.POST['PuanGirisi']
        #print("postları aldı",LisansTuru, PuanTuru, PuanGirisi)

    #print("if ööncesi koşu")
    if(LisansTuru=='2'):
        #print("lisansturu2 onay")
        onlisanslist=OnLisans2020.objects.all()
        onlisanslist=onlisanslist.filter(PuanTuru__exact='TYT').filter(EnKucukPuan__lte=PuanGirisi).order_by('-EnKucukPuan')
        context={'object_list':onlisanslist}
        template_name = 'apptercihrobotu/home.html'
        return render(request,template_name,context)

    elif (LisansTuru=='3'):
        #print("lisansturu3 onay")
        #print(PuanTuru)
        # if PuanTuru=='1':
        #     PuanTuru="SAY"
        #     print(PuanTuru)
        # elif PuanTuru=='2':
        #     PuanTuru="SOZ"
        # elif PuanTuru=='3':
        #     PuanTuru="EA"
        # elif PuanTuru=='4':
        #     PuanTuru="DİL"
        #lisanslistviewcagır
        #print("lisansturu4 onay")
        lisanslist=Lisans42020.objects.all()
        lisanslist=lisanslist.filter(PuanTuru__exact=PuanTuru).filter(EnKucukPuan__lte=PuanGirisi).order_by('-EnKucukPuan')
        context={'object_list':lisanslist}
        template_name = 'apptercihrobotu/home.html'
        return render(request,template_name,context)
        
    #else alert secim yapmadınız uyarısı

    return HttpResponse("İlginç Bir Hata")       

        #return HttpResponseRedirect(reverse(('apptercihrobotu:home_tercihrobotu'), args=(LisansTuru,PuanTuru,PuanGirisi)))

Apps/apptercihrobotu/templates/apptercihrobotu/#####home.html
{% extends "users/base.html" %}
{% block content %}







<div class="container">
    <div class="row" style="margin-top: 0px;height: 10px;"></div>
    <div class="row">
        <div class="col" style="padding-top: 8px;"><select
                class="border rounded border-primary shadow-sm form-control-lg" data-toggle="tooltip" data-bs-tooltip=""
                name="LisansTuru" title="Lisans Türü" style="margin-right: 8px;">
                <option value="" selected="">-----</option>
                <option value="">Ön Lisans</option>
                <option value="">Lisans</option>
            </select>
            <select class="border rounded border-primary shadow-sm form-control-lg" data-toggle="tooltip"
                data-bs-tooltip="" name="PuanTuru" title="Puan Türü" style="margin-right: 8px;">
                <option value="" selected="">-----</option>
                <option value="">SAY</option>
                <option value="">SOZ</option>
                <option value="">EA</option>
                <option value="">DİL</option>
                <option value="">TYT</option>
            </select><input class="border rounded border-primary shadow-sm form-control-lg" type="number"
                data-toggle="tooltip" data-bs-tooltip="" title="Puanınız" min="0" max="600" name="PuanGirisi"
                required="" style="width: 150px;" placeholder="Puanınız"></div>
        <div class="col" style="padding-top: 8px;"><button class="btn btn-primary btn-lg" type="submit">Onayla</button>
        </div>
    </div>
    <div class="row" style="margin-top: 0px;height: 80px;"></div>
    <div class="row">
        <div class="col" style="border-width: 1px;border-style: solid;">
            <p>Üniversite</p><input type="search" name="AraUniversite" placeholder="Ara" style="margin-bottom: 10px;">
        </div>
        <div class="col" style="border-width: 1px;border-style: solid;">
            <p>Bölüm</p><input type="search" name="AraBolum" placeholder="Ara" style="margin-bottom: 10px;">
        </div>
        <div class="col" style="border-width: 1px;border-style: solid;">
            <p>En Küçük Puan</p>
        </div>
        <div class="col" style="border-width: 1px;border-style: solid;">
            <p>En Büyük Puan</p>
        </div>
    </div>
        {% for object in object_list %}
        <div class="row">
            <div class="col" style="border-width: 1px;border-style: solid;">{{object.UniversiteAdi}}</div>
            <div class="col" style="border-width: 1px;border-style: solid;">{{object.BolumAdi}}</div>
            <div class="col" style="border-width: 1px;border-style: solid;">{{object.EnKucukPuan}}</div>
            <div class="col" style="border-width: 1px;border-style: solid;">{{object.EnBuyukPuan}}</div>
        </div>
        {% endfor %}
        <div class="row">
            <div class="col" style="padding-top: 10px;">
                <nav class="d-xl-flex justify-content-xl-center align-items-xl-center">
                    {% comment %} <div class="pagination">
                        <span class="step-links">
                            {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; İlk</a>
                            <a href="?page={{ page_obj.previous_page_number }}">Önceki</a>
                            {% endif %}

                            <span class="current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>

                            {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">Sonraki</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">Son &raquo;</a>
                            {% endif %}
                        </span>
                    </div> {% endcomment %}
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page=1">&laquo; İlk</a></li>
                        <li class="page-item"><a class="page-link"
                                href="?page={{ page_obj.previous_page_number }}">Önceki</a></li>
                        {% endif %}
                        <li class="page-item disabled"><a class="page-link" href="#">Sayfa: {{ page_obj.number }} Toplam:
                                {{ page_obj.paginator.num_pages }} </a></li>
                        {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link"
                                href="?page={{ page_obj.next_page_number }}">Sonraki</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Son
                                &raquo;</a></li>
                        {% endif %}

                    </ul>
                </nav>
            </div>
        </div>
</div>





{% endblock content %}

Apps/apptercihrobotu/templates/apptercihrobotu/####home.html
{% extends "users/base.html" %}
{% block content %}



<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>



<div class="container">
    <div class="row" style="margin-top: 0px;height: 10px;"></div>
    <form action="{% url 'apptercihrobotu:sonuchesapla' %}" method="POST">
        {% csrf_token %}
        <div class="row">

            <div class="col" style="padding-top: 8px;"><select
                    class="border rounded border-primary shadow-sm form-control-lg" data-toggle="tooltip"
                    data-bs-tooltip="" name="LisansTuru" id="LisansTuru" title="Lisans Türü" style="margin-right: 8px;">
                    <option value="1" selected="">-----</option>
                    <option value="2">Ön Lisans</option>
                    <option value="3">Lisans</option>
                </select>
                <select class="border rounded border-primary shadow-sm form-control-lg" data-toggle="tooltip"
                    data-bs-tooltip="" name="PuanTuru" id="PuanTuru" title="Puan Türü" style="margin-right: 8px;">
                    <option value="1" selected="">-----</option>
                    <option value="SAY" name="3">SAY</option>
                    <option value="SÖZ" name="3">SOZ</option>
                    <option value="EA" name="3">EA</option>
                    <option value="DİL" name="3">DİL</option>
                    <option value="TYT" name="2">TYT</option>
                </select><input class="border rounded border-primary shadow-sm form-control-lg" type="number"
                    data-toggle="tooltip" data-bs-tooltip="" title="Puanınız" min="0.0" max="600.0" step="0.00001"
                    name="PuanGirisi" id="PuanGirisi" required="" style="width: 150px;" placeholder="Puanınız">
            </div>
            <div class="col" style="padding-top: 8px;"><button class="btn btn-primary btn-lg"
                    type="submit">Onayla</button>
            </div>

        </div>
    </form>
    <div class="row" style="margin-top: 0px;height: 80px;"></div>
    <div class="row">
        <div class="col" style="border-width: 1px;border-style: solid;">
            <p>Üniversite</p><input type="search" id="AraUniversite" name="AraUniversite" placeholder="Ara" style="margin-bottom: 10px;">
        </div>
        <div class="col" style="border-width: 1px;border-style: solid;">
            <p>Bölüm</p><input type="search" id="AraBolum" name="AraBolum" placeholder="Ara" style="margin-bottom: 10px;">
        </div>
        <div class="col" style="border-width: 1px;border-style: solid;">
            <p>En Küçük Puan</p>
        </div>
        <div class="col" style="border-width: 1px;border-style: solid;">
            <p>En Büyük Puan</p>
        </div>
    </div>
    {% for object in object_list %}
    <div class="row">
        <div class="col" style="border-width: 1px;border-style: solid;">{{object.UniversiteAdi}}</div>
        <div class="col" style="border-width: 1px;border-style: solid;">{{object.BolumAdi}}</div>
        <div class="col" style="border-width: 1px;border-style: solid;">{{object.EnKucukPuan}}</div>
        <div class="col" style="border-width: 1px;border-style: solid;">{{object.EnBuyukPuan}}</div>
    </div>
    {% endfor %}
    <div class="row">
        <div class="col" style="padding-top: 10px;">
            <nav class="d-xl-flex justify-content-xl-center align-items-xl-center">
                {% comment %} <div class="pagination">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; İlk</a>
                        <a href="?page={{ page_obj.previous_page_number }}">Önceki</a>
                        {% endif %}

                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>

                        {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">Sonraki</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">Son &raquo;</a>
                        {% endif %}
                    </span>
                </div> {% endcomment %}
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">&laquo; İlk</a></li>
                    <li class="page-item"><a class="page-link"
                            href="?page={{ page_obj.previous_page_number }}">Önceki</a></li>
                    {% endif %}
                    <li class="page-item disabled"><a class="page-link" href="#">Sayfa: {{ page_obj.number }} Toplam:
                            {{ page_obj.paginator.num_pages }} </a></li>
                    {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Sonraki</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Son
                            &raquo;</a></li>
                    {% endif %}

                </ul>
            </nav>
        </div>
       
    </div>
</div>

<script>
    var $LisansTuru = $('#LisansTuru'),
        $PuanTuru = $('#PuanTuru'),
        $options = $PuanTuru.find('option');

    $LisansTuru.on('change', function () {
        $PuanTuru.html($options.filter('[name="' + this.value + '"]'));
    }).trigger('change');

</script>



{% endblock content %}

Apps/apptercihrobotu/templates/apptercihrobotu/###home.html
    {% comment %} function searchuni(){
      formdata = new FormData();
      formdata.append('csrfmiddlewaretoken', '{{ csrf_token }}');
      formdata.append('university', $('#AraUniversite').val());
      formdata.append('bolum', $('#AraBolum').val());

      $.ajax({
        type: 'POST',
        url: "{% url 'apptercihrobotu:searchuni' %}",
        data        : formdata,
        cache       : false,
        contentType : false,
        processData : false,
        success: function (response) {
          //location.reload();
          console.log("a");
          var c = response['onnn'];
          console.log(c);


        },
        error: function (response) {
          console.log("b");

        }
      })
    }

Apps/apptercihrobotu/templates/apptercihrobotu/#home.html
{% extends "users/base.html" %}
{% block content %}



<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>



<div class="container">
    <div class="row" style="margin-top: 0px;height: 10px;"></div>
    <form action="{% url 'apptercihrobotu:sonuchesapla' %}" method="POST">
        {% csrf_token %}
        <div class="row">

            <div class="col" style="padding-top: 8px;"><select
                    class="border rounded border-primary shadow-sm form-control-lg" data-toggle="tooltip"
                    data-bs-tooltip="" name="LisansTuru" id="LisansTuru" title="Lisans Türü" style="margin-right: 8px;">
                    <option value="1" selected="">-----</option>
                    <option value="2">Ön Lisans</option>
                    <option value="3">Lisans</option>
                </select>
                <select class="border rounded border-primary shadow-sm form-control-lg" data-toggle="tooltip"
                    data-bs-tooltip="" name="PuanTuru" id="PuanTuru" title="Puan Türü" style="margin-right: 8px;">
                    <option value="1" selected="">-----</option>
                    <option value="SAY" name="3">SAY</option>
                    <option value="SÖZ" name="3">SOZ</option>
                    <option value="EA" name="3">EA</option>
                    <option value="DİL" name="3">DİL</option>
                    <option value="TYT" name="2">TYT</option>
                </select><input class="border rounded border-primary shadow-sm form-control-lg" type="number"
                    data-toggle="tooltip" data-bs-tooltip="" title="Puanınız" min="0.0" max="600.0" step="0.00001"
                    name="PuanGirisi" id="PuanGirisi" required="" style="width: 150px;" placeholder="Puanınız">
            </div>
            <div class="col" style="padding-top: 8px;"><button class="btn btn-primary btn-lg"
                    type="submit">Onayla</button>
            </div>

        </div>
    </form>
    <div class="row" style="margin-top: 0px;height: 80px;"></div>
    <div class="row">
        <div class="col" style="border-width: 1px;border-style: solid;">
            <p>Üniversite</p><input type="search" id="AraUniversite" name="AraUniversite" placeholder="Ara" style="margin-bottom: 10px;">
        </div>
        <div class="col" style="border-width: 1px;border-style: solid;">
            <p>Bölüm</p><input type="search" id="AraBolum" name="AraBolum" placeholder="Ara" style="margin-bottom: 10px;">
        </div>
        <div class="col" style="border-width: 1px;border-style: solid;">
            <p>En Küçük Puan</p>
        </div>
        <div class="col" style="border-width: 1px;border-style: solid;">
            <p>En Büyük Puan</p>
        </div>
    </div>
    {% for object in object_list %}
    <div class="row">
        <div class="col" style="border-width: 1px;border-style: solid;">{{object.UniversiteAdi}}</div>
        <div class="col" style="border-width: 1px;border-style: solid;">{{object.BolumAdi}}</div>
        <div class="col" style="border-width: 1px;border-style: solid;">{{object.EnKucukPuan}}</div>
        <div class="col" style="border-width: 1px;border-style: solid;">{{object.EnBuyukPuan}}</div>
    </div>
    {% endfor %}
    <div class="row">
        <div class="col" style="padding-top: 10px;">
            <nav class="d-xl-flex justify-content-xl-center align-items-xl-center">
                {% comment %} <div class="pagination">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; İlk</a>
                        <a href="?page={{ page_obj.previous_page_number }}">Önceki</a>
                        {% endif %}

                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>

                        {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">Sonraki</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">Son &raquo;</a>
                        {% endif %}
                    </span>
                </div> {% endcomment %}
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">&laquo; İlk</a></li>
                    <li class="page-item"><a class="page-link"
                            href="?page={{ page_obj.previous_page_number }}">Önceki</a></li>
                    {% endif %}
                    <li class="page-item disabled"><a class="page-link" href="#">Sayfa: {{ page_obj.number }} Toplam:
                            {{ page_obj.paginator.num_pages }} </a></li>
                    {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Sonraki</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Son
                            &raquo;</a></li>
                    {% endif %}

                </ul>
            </nav>
        </div>
       
    </div>
</div>

<script>
    var $LisansTuru = $('#LisansTuru'),
        $PuanTuru = $('#PuanTuru'),
        $options = $PuanTuru.find('option');

    $LisansTuru.on('change', function () {
        $PuanTuru.html($options.filter('[name="' + this.value + '"]'));
    }).trigger('change');

</script>



{% endblock content %}