Apps/blogs/urls.py
# blogs/urls.py
from django.urls import path
#from .views import HomePageView
from . import views
from os import name
from django.urls import path
from .views import (MakaleListView, MakaleDetailView, MakaleCreateView ,
MakaleUpdateView,MakaleDeleteView,)


# app_name = 'blogs'
# urlpatterns = [
#     path('', views.makale_home, name='makale_home'),
#     path('create_makale/', views.create_makale, name='create_makale'),
#     path('delete_makale/<int:post_id>', views.delete_makale, name='delete_makale'),
#     path('edit_makale/', views.edit_makale, name='edit_makale'),
# ]
app_name = 'blogs'
urlpatterns = [
    path('blogs/<int:pk>/delete/', MakaleDeleteView.as_view(), name='makale_delete'),
    path('new/', MakaleCreateView.as_view(), name='makale_new'),
    path('', MakaleListView.as_view(), name='makale_home'),
    path('detail/<int:pk>/', MakaleDetailView.as_view(), name= 'makale_detail'),
    path('blogs/<int:pk>/edit/',MakaleUpdateView.as_view(), name='makale_edit'),
]

Apps/comments/urls.py
from django.urls import path

from . import views

app_name = 'comments'
urlpatterns = [
    path('', views.index, name='index'),
    path('createpost/', views.createpost, name='createpost'),
    path('deletepost/<int:post_id>', views.deletepost, name='deletepost'),
    path('editpost/', views.editpost, name='editpost'),
]

University/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('comments/', include('Apps.comments.urls')),
    path('universities/', include('Apps.universities.urls')),
    path('', include('Apps.users.urls')),
    path('apptercih/',include('Apps.apptercih.urls')),
    path('calendar/',include('Apps.calendars.urls')),
    path('blogs/',include('Apps.blogs.urls')),
    path('tercihrobotu/',include('Apps.apptercihrobotu.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Apps/blogs/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.timezone import now


class Blog(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        #get_user_model(),
        #'auth.User',
        settings.AUTH_USER_MODEL,
        
        on_delete=models.CASCADE,
    )
    body = models.TextField()
    updated_on = models.DateTimeField(auto_now= True)
    created_on = models.DateTimeField(auto_now_add=True)

    #date = models.DateTimeField(auto_now_add=True,blank=True)   önceden vardı
    ##date = models.DateTimeField(default=now, editable=False)   sonra yaptım

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title   # burda primary key mi yaptı yani aynı başlıkta 2 post olmazmı ?

    def get_absolute_url(self): 
        return reverse('blogs:makale_detail', args=[str(self.id)])


class Comment(models.Model):
    text = models.CharField(max_length=200)
    created_time = models.DateTimeField('date published')
    is_edited = models.BooleanField(default=False)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, related_name='commentList', on_delete=models.CASCADE)
    likes = models.IntegerField(default=0)

    def __str__(self):
        return self.text

Apps/blogs/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from django.views.generic.edit import CreateView, UpdateView,DeleteView
from django.urls import reverse_lazy
from .models import Blog, Comment

# Create your views here.


# def makale_home(request):
#     return render(request, 'blogs/makale_home.html', {'postList': Post.objects.order_by('-created_time')[:20]})


# def create_makale(request):

#     if request.method == 'POST':
#         textField = request.POST['textField']
#         created_time = timezone.now()
#         is_edited = False
#         likes = 0
#         newMakale = Post(text=textField, created_time=created_time, is_edited=is_edited, likes=likes, owner=request.user)
#         newMakale.save()
#         return render(request, 'blogs/makale_home.html', {'postList': Post.objects.order_by('-created_time')[:20], 'alert_message': 'Başarılı', 'alertColor': 'successfull'})
#     return render(request, 'blogs/makale_home.html', {'postList': Post.objects.order_by('-created_time')[:20], 'alert_message': 'Yeni Bir Blog Oluşturulamadı Lütfen Tekrar deneyin', 'alertColor': 'dangerr'})
    
    
# def deletepost(request, post_id):
#     post = get_object_or_404(Post, pk=post_id)

#     if(post.owner.id == request.user.id):
#         try:
#             postText = post.text
#             post.delete()
#             return render(request, 'blogs/index.html', {'postList': Post.objects.order_by('-created_time')[:20], 'alert_message': 'Başarılı', 'alertColor': 'successfull'})
#         except:
#             return render(request, 'blogs/index.html', {'postList': Post.objects.order_by('-created_time')[:20], 'alert_message': 'Bloğunuz silinemedi Lütfen Tekrar deneyin', 'alertColor': 'dangerr'})
#     else:
#         return render(request, 'blogs/index.html', {'postList': Post.objects.order_by('-created_time')[:20], 'alert_message': 'Sadece kendi blogunuzu silebilirsiniz', 'alertColor': 'dangerr'})


# def editpost(request):
#     # request should be ajax and method should be POST.
#     if request.is_ajax and request.method == "POST":
#         dataList = request.body.decode('utf-8').split('&')
#         post_id= 0
#         post_text= ""
#         for item in dataList:
#             value = item.split('=')
#             if(value[0] == 'post_id'):
#                 post_id = value[1]
#             elif(value[0] == 'post_text'):
#                 post_text = value[1]
#             else:
#                 continue

#         post = get_object_or_404(Post, pk=post_id)
#         if(post.owner.id == request.user.id):
#             post.text = post_text
#             post.save()
#             return JsonResponse({'alert_message': 'Başarılı', 'alertColor': 'successfull'}, status = 200)
#         else:
#             return JsonResponse({'alert_message': 'Sizin bu blogu silmeye yetkiniz yok', 'alertColor': 'dangerr'}, status = 400)

#     return JsonResponse({'alert_message': 'Bir hata ile karşılaşıldı', 'alertColor': 'dangerr'}, status = 400)




################


class MakaleListView(ListView):
    model = Blog
    template_name = 'blogs/blog_home.html'

class MakaleDetailView(DetailView):
    model = Blog
    template_name = 'blogs/blog_detail.html'

class MakaleCreateView(CreateView): # new
    model = Blog
    template_name = 'blogs/blog_new.html'
    fields = ['title', 'body']
    #Makale.author = User
    #fields = ['title', 'author', 'body']
    def form_valid(self, form):
        form.instance.author_id = self.request.user.pk
        return super().form_valid(form)

class MakaleUpdateView(UpdateView): # new
    model = Blog
    template_name = 'blogs/makale_edit.html'
    fields = ['title', 'body']  

class MakaleDeleteView(DeleteView): # new
    model = Blog
    template_name = 'blogs/makale_delete.html'
    success_url = reverse_lazy('blogs:makale_home')



def createcomment(request):
    if request.method == 'POST':
        textField = request.POST['textField']
        blog_id = request.POST['blog_id']
        blog = Blog.objects.get(pk=blog_id)
        created_time = timezone.now()
        is_edited = False
        likes = 0
        newPost = Comment(text=textField, created_time=created_time, is_edited=is_edited, likes=likes, owner=request.user, blog=blog)
        newPost.save()
        return render(request, 'comments/index.html', {'postList': Post.objects.order_by('-created_time')[:20], 'alert_message': 'Başarılı', 'alertColor': 'successfull'})
    return render(request, 'comments/index.html', {'postList': Post.objects.order_by('-created_time')[:20], 'alert_message': 'Yeni Bir Blog Oluşturulamadı Lütfen Tekrar deneyin', 'alertColor': 'dangerr'})
    

Apps/blogs/templates/blogs/###makale_home.html
{% comment %} {% extends 'appmakales/base.html' %} {% endcomment %}
{% block content_appmakales %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .head_text {
        color: white;
    }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to my awesome Blog </h3>
                    <p class="text-light">We Love Django As much as you do..! &nbsp
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            <!-- {% for makale in makale_list %} -->
            {% for makale in object_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ makale.title }}</h2>
                    <p class="card-text text-muted h6">{{ makale.author }} | {{ makale.created_on}} </p>
                    <p class="card-text">{{makale.body|slice:":200" }}</p>
                    <a href="{% url 'blogs:makale_detail' makale.pk  %}" class="btn btn-primary">Read More
                        &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
        <!--{% block sidebar %} {% include 'blogs/sidebar.html' %} {% endblock sidebar %}-->
    </div>
</div>


{% endblock content_appmakales%}


{% comment %}
{% extends 'blogs/base.html' %} {% block contentt %}

{% for makale in object_list %}

<div class="card">
    <div class="card-header">
        <span class="font-weight-bold">{{ makale.title }}</span> &middot;
        <span class="text-muted"> by {{ makale.author }} | {{ makale.date }}</span>
    </div>
    <div class="card-body">{{ makale.body }}</div>
    <div class="card-footer text-center text-muted">
        <a href="{% url 'blogs:makale_edit' makale.pk %}">Düzenle</a> |
        <a href="{% url 'blogs:makale_delete' makale.pk %}">Kaldır</a>
    </div>
</div>
<br />

{% endfor %} {% endblock contentt %}
{% endcomment %}

Apps/blogs/templates/blogs/#base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Hello, world! title </title>
  </head>
    
    
    
    
  <body>

      
    
{% comment %}       
      <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
 
          
          <a class="btn btn-outline-secondary" href="{% url 'blogs:makale_home' %}" role="button">Home</a>
          
{% if user.is_authenticated %}
  <div class="btn-group" role="group" aria-label="loginsignupbuttons">
          <a class="btn btn-outline-secondary" href="{% url 'blogs:makale_new' %}" role="button">New Post</a>
          <a class="btn btn-outline-secondary" href="#" role="button">{{ user.username }}</a>
          <a class="btn btn-outline-secondary" href="{% url 'logout' %}" role="button">Logout</a>
          
</div>
{% else %}

          <div class="btn-group" role="group" aria-label="loginsignupbuttons">
          <a class="btn btn-outline-secondary" href="{% url 'login' %}" role="button">Login</a>
          <a class="btn btn-outline-secondary" href="{% url 'signup' %}" role="button">Signup</a>
</div>
{% endif %}

</nav> {% endcomment %}

{% block content %} {% endblock content %}


          

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

Apps/blogs/templates/blogs/#friendship.html
<html>

<body>

deneme 123

</body>


</html>

Apps/blogs/templates/blogs/#makale_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Makale</title>
</head>
<body>

makale home hoşgeldiniz
    
</body>
</html>

Apps/blogs/templates/blogs/#profile.html
{% extends 'base.html' %}  {% block content %}
   
    <div class="container" style="margin: 0px 30px;">
        <h1>USERNAME</h1>
        <div>
            <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item" role="presentation"><a class="nav-link" role="tab" data-toggle="tab" href="#tab-1">posts</a></li>
                <li class="nav-item" role="presentation"><a class="nav-link" role="tab" data-toggle="tab" href="#tab-2">messages</a></li>
                <li class="nav-item" role="presentation"><a class="nav-link" role="tab" data-toggle="tab" href="#tab-3">following</a></li>
                <li class="nav-item" role="presentation"><a class="nav-link" role="tab" data-toggle="tab" href="#tab-4">followers</a></li>
                <li class="nav-item" role="presentation"><a class="nav-link active" role="tab" data-toggle="tab" href="#tab-5">friends</a></li>
                <li class="nav-item" role="presentation"><a class="nav-link" role="tab" data-toggle="tab" href="#tab-6">settings</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane" role="tabpanel" id="tab-1">
                    <p>Content for tab 1.</p>
                </div>
                <div class="tab-pane" role="tabpanel" id="tab-2">
                    <p>Content for tab 2.</p>
                </div>
                <div class="tab-pane" role="tabpanel" id="tab-3">
                    <p>Content for tab 3.</p>
                </div>
                <div class="tab-pane" role="tabpanel" id="tab-4">
                    <p>Tab content.</p>
                </div>
                <div class="tab-pane active" role="tabpanel" id="tab-5">
                    <p>Tab content. 5</p>
                </div>
                <div class="tab-pane" role="tabpanel" id="tab-6">
                    <p>Tab content.</p>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

Apps/blogs/templates/blogs/#signup.html
{% extends 'base.html' %}
{% block content %}
<h2>Signup</h2>
<form method="post">
{% csrf_token %}
{{ form.as_p }}
<button type="submit">Signup</button>
</form>
{% endblock content %}

Apps/blogs/templates/blogs/base.html
{% extends 'users/base.html' %}

{% block CustomStyle %}
<style>
    .cardShadow {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>
{% endblock CustomStyle %}



{% block content %}

 <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    {% if user.is_authenticated %}
    <div class="btn-group" role="group" aria-label="loginsignupbuttons">
        <a class="btn btn-outline-secondary" href="{% url 'blogs:makale_new' %}" role="button">Yeni Makale</a>
        <a class="btn btn-outline-secondary" href="#" role="button">{{ user.username }}</a>
    </div>
    {% else %}
    {% endif %}
</nav> 


{% block content_blogs %}
{% endblock content_blogs %}

{% endblock content %}

{% block Customscript %}
{% endblock Customscript %}

Apps/blogs/templates/blogs/blog_detail.html
{% extends 'blogs/base.html' %}

{% block content_blogs %}
<div class="container">
  <div class="row">
    <div class="col-md-8 card cardShadow mb-4 mt-3 left top">
      <div class="card-body">
        <h1>{% block title %} {{ blog.title }} {% endblock title %}</h1>
        <p class="text-muted">{{ blog.author }} | {{blog.created_on }}</p>
        <p class="card-text ">{{ blog.body | safe | linebreaks}}</p>
      </div>
      <div class="row">
        <div class="container-fluid mb-5">
          <div class="row justify-content-center">
              <div class="col-10">

                <form id="sharecomment" class="mt-5" action="{% url 'blogs:createcomment' %}" method="POST">
                    {% csrf_token %}
                    <div>
                        <label for="textField">Düşüncelerinizi Paylaşın</label>
                        <textarea class="form-control" name="textField" id="textField" {% if not user.is_authenticated %} disabled  {% endif %} placeholder="Ne düşünüyorsun? Düşüncelerini Paylaş" required></textarea>
                    </div>
                    <div class="float-right mt-2">
                        <button type="submit" class="btn btn-primary ">Kaydet</button>
                    </div>
                </form>

                <h3 class="mx-auto my-5">Son Yorumlar</h3>
                <div class="w-100"></div> 
                {% for o in blog.commentList.all %}
                  <div class="card mt-3">
                      <div class="card-body">
                          {% if user == o.owner %}
                              <div class="btn-group dropright" data-bs-hover-animate="pulse" style="position: absolute; right: 0px; width: 3%; margin-top: -20px; margin-right: 20px;">
                                  <a class="btn" data-toggle="dropdown" data-display="static" aria-haspopup="true" aria-expanded="true"><i class="fa fa-navicon" style="font-size: 20px; color:grey"></i></a>
                                  <div class="dropdown-menu dropdown-menu-lg-right">
                                      <a class="dropdown-item" id="btnPost_{{o.id}}" href="javascript:openModal('{{o.id}}','{{o.text}}','{{o.owner}}');">Düzenle</a>
                                      <a href="{% url 'comments:deletepost' o.id %}" class="dropdown-item">Sil</a>
                                  </div>
                              </div>
                          {% endif %}    
                          <blockquote class="blockquote mb-0">
                            <p id=post_{{o.id}}>{{o.text}}</p>
                          </blockquote>
                      </div>
                      <div class="card-footer">
                          <small class="text-muted">- {{o.owner}}</small>
                          <small class="text-muted"> {{o.created_time}}</small>
                      </div>
                  </div>
                {% endfor %}
              </div>
          </div>
        </div>
      </div>
    </div>
    {% block sidebar %} {% include 'blogs/sidebar.html' %} {% endblock sidebar %}
  </div>
</div>





<div class="modal fade" id="editPost" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Yorum Düzenleme</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Sahibi: </label>
                        <input type="text" class="form-control" id="post_owner" disabled>
                        </div>
                        <div class="form-group">
                        <label for="message-text" class="col-form-label">Yazı: </label>
                        <textarea class="form-control" id="post_text"></textarea>
                        </div>
                        <!-- <input type="text" class="form-control" id="post_id" disabled style="visibility:hidden"> -->
                    </div>
                </form>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">İptal</button>
                <button id="saveChanges" type="submit" class="btn btn-primary">Kaydet</button>
            </div>
      </div>
    </div>
  </div>
  {% endblock content_blogs %}


{% block Customscript %}


  <script>
    $("#sharecomment").submit(function () {
      // if(lastitem == ''){
      //     var input = $("<input>").attr("name", "city").val('cityNull');
      //     $(this).append(input);
      // }
      // else{
      //     cityInput = lastitem.getAttribute('id');
      //     var input = $("<input>").attr("name", "city").val(cityInput);
      //     $(this).append(input);
      // }
        console.log("aa");
      return false;
    });
  </script>

    <script>
        var lastPostId = 0;
        var lastPostText = 0;
        var ownerId = 0;

        function openModal(post_id, post_text, post_owner) {
            $('#editPost').modal();
            $('#editPost').trigger('focus');
            $('#post_text').val(post_text);
            $('#post_owner').val(post_owner);
            lastPostId = post_id;
            lastPostText = post_text;
            ownerId = post_owner;
        }

        $("#saveChanges").click(function (e) {

            var currentText = $('#post_text').first().val();
            if(lastPostText != currentText){
                // preventing from page reload and default actions

                $.ajax({
                    type: 'POST',
                    url: "{% url 'comments:editpost' %}",
                    data: {
                        post_id: lastPostId,
                        post_text: currentText,
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                    },

                    success: function (response) {
                        $('#post_' + lastPostId).text(currentText);
                        $('#post_' + lastPostId).trigger('focus');
                        $('#editPost').modal('toggle');

                        var btnProperties = document.getElementById('btnPost_' + lastPostId);
                        btnProperties.setAttribute('href', "javascript:openModal('" + lastPostId + "','"  + currentText + "','" + ownerId + "');");
                        var x = document.getElementById("snackbar1");
                        x.className = "show makegreen";
                        text = response['alert_message'];
                        x.innerHTML = "<b>"+ text +"</b>"
                        setTimeout(function(){ x.className = x.className.replace("show makegreen", "makegreen"); }, 3000);
                    },
                    error: function (response) {
                        var x = document.getElementById("snackbar1");
                        x.className = "show makered";
                        text = response['alert_message'];
                        x.innerHTML = "<b>"+ text +"</b>"
                        setTimeout(function(){ x.className = x.className.replace("show makered", "makered"); }, 3000);
                    }
                })
            }
        })
    </script>
{% endblock Customscript %}






<!-- 
{% comment %} {% extends 'blogs/base.html' %}
{% block content %}

<div class="card">
  <div class="card-header">
    <span class="font-weight-bold">{{ makale.title }}</span> &middot;
    <span class="text-muted">        by {{ makale.author }} | {{ makale.date }}</span>
  </div>
  <div class="card-body">{{ makale.body }}</div>
  <div class="card-footer text-center text-muted">
    <a href="{% url 'blogs:makale_edit' makale.pk %}">Edit</a> |
    <a href="{% url 'blogs:makale_delete' makale.pk %}">Delete</a>
  </div>
</div>


{% endblock content %} {% endcomment %} -->

Apps/blogs/templates/blogs/blog_home.html
{% extends 'blogs/base.html' %}
{% block content_blogs %}

<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% comment %} {% for makale in makale_list %} {% endcomment %}
            {% for makale in object_list %}
            <div class="card cardShadow cardShadow mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ makale.title|slice:":50" }}</h2>
                    <p class="card-text text-muted h6">{{ makale.author }} | {{ makale.created_on}} </p>
                    <p class="card-text">{{makale.body|slice:":200" | linebreaks }}</p>
                    <a href="{% url 'blogs:makale_detail' makale.pk  %}" class="btn btn-primary">Devamını oku
                        &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
        {% block sidebar %} {% include 'blogs/sidebar.html' %} {% endblock sidebar %}
    </div>
</div>


{% endblock content_blogs %}


<!-- {% comment %}
{% extends 'blogs/base.html' %} {% block contentt %}

{% for makale in object_list %}

<div class="card">
    <div class="card-header">
        <span class="font-weight-bold">{{ makale.title }}</span> &middot;
        <span class="text-muted"> by {{ makale.author }} | {{ makale.date }}</span>
    </div>
    <div class="card-body">{{ makale.body }}</div>
    <div class="card-footer text-center text-muted">
        <a href="{% url 'blogs:makale_edit' makale.pk %}">Düzenle</a> |
        <a href="{% url 'blogs:makale_delete' makale.pk %}">Kaldır</a>
    </div>
</div>
<br />

{% endfor %} {% endblock contentt %}
{% endcomment %} -->

Apps/blogs/templates/blogs/blog_new.html
{% extends 'blogs/base.html' %}
{% block content_blogs %}
<h1>Yeni Rehber Yazısı</h1>
<form action="" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Save">
</form>
{% endblock content_blogs %}

Apps/blogs/templates/blogs/makale_delete.html
{% extends 'blogs/base.html' %}
{% block content_appmakales %}
<h1>Makele Silme</h1>
<form action="" method="post">{% csrf_token %}
<p> "{{ makale.title }}" Makalesini silmek istediğinizden eminmisiniz?</p>
<input type="submit" value="Confirm">
</form>
{% endblock content_appmakales %}

Apps/blogs/templates/blogs/makale_edit.html
{% extends 'blogs/base.html' %}
{% block content_blogs %}
<h1>Makale Düzenle</h1>
<form action="" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Update">
</form>
{% endblock content_blogs %}

Apps/blogs/templates/blogs/sidebar.html
{% block sidebar %}

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card cardShadow my-4">
        <h5 class="card-header">yan bar</h5>
    <div class="card-body">
        <p class="card-text"> buraya son makaleler , yazarın son makaleleri , gelebilir vs</p>
        
    </div>
</div>
</div>

{% endblock sidebar %}