Apps/universities/urls.py
from django.urls import path

from . import views

app_name = 'universities'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:university_id>', views.detail, name='detail'),
    path('createUniversity/', views.createUniversity, name='createUniversity'),
    path('submitcreateUniversity/', views.submitcreateUniversity, name='submitcreateUniversity'),
    path('searchUniversity/', views.searchUniversity, name='searchUniversity'),
    path('search/<str:searchText>/<str:searchCity>', views.searchUniversityPage, name='searchUniversityPage'),
    path('editUniversity/', views.editUniversity, name='editUniversity'),
]

Apps/users/urls.py
from .views import VerificationView
from django.contrib.auth.views import PasswordResetDoneView
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from django.urls import reverse_lazy

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profileEdit/', views.profileEdit, name='profileEdit'),
    path('universities/', views.universityList, name='universityList'),
    # path('password_change/', auth_views.PasswordChangeView.as_view(template_name='users/password_change.html', success_url=reverse_lazy('users:password_change_done'),),
    #     name='password_change'),
    path('password_change/',views.sayfasifredegis,name="password_change"),
    path('password_change2/',views.password_change,name="password_change2"),
    path('password_change_done/',views.passwordChangeDone,name="password_change_done"),

    # path('password_change_done/', auth_views.PasswordChangeDoneView.as_view(
    #     template_name='users/password_change_done.html'), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(email_template_name='users/password_reset_email.html',
        html_email_template_name = 'users/html_password_reset_email.html',
        success_url=reverse_lazy('users:password_reset_done'), template_name='users/password_reset.html'), name='password_reset'),
    path('password_reset_send/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_send.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy(
        'users:password_reset_complete'), template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('activate/<uidb64>/<token>', VerificationView.as_view(), name='activate'),
    path('signup_completed',views.funcsignupcompleted,name='activated'),
    path('password_reset2/',views.password_reset2,name='password_reset2'),
    path('kullanicisozlesmesi/', views.kullanicisozlesmesi, name='kullanicisozlesmesi'),
    path('gizliliksozlesmesi/', views.gizliliksozlesmesi, name='gizliliksozlesmesi'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('subscribed/<str:email>', views.aftersubsribe, name='aftersubsribe')
]

University/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('comments/', include('Apps.comments.urls')),
    path('universities/', include('Apps.universities.urls')),
    path('', include('Apps.users.urls')),
    path('apptercih/',include('Apps.apptercih.urls')),
    path('calendar/',include('Apps.calendars.urls')),
    path('blogs/',include('Apps.blogs.urls')),
    path('tercihrobotu/',include('Apps.apptercihrobotu.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Apps/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone

class CustomUser(AbstractUser):
    age = models.PositiveIntegerField(null=True, blank=True)

    followingList = models.ManyToManyField('self', related_name='followerList',symmetrical=False,  blank=True)
    def GetFollowingList(self):
        return "\n".join([p.username for p in self.followingList.all()])

    def GetFollowerList(self):
        return "\n".join([p.username for p in self.followerList.all()])


    GetFollowingList.short_description = 'Following'
    GetFollowerList.short_description = 'Follower'

class Subscribers(models.Model):
    email = models.EmailField(max_length=200)
    is_active = models.BooleanField(default=True)
    createdTime = models.DateTimeField(default=timezone.now, blank=True)

    def __str__(self):
        return self.email

    class Meta:
        verbose_name_plural = "Subscribers"

Apps/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ('age',)
        

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = UserChangeForm.Meta.fields
        

Apps/users/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import authenticate, logout as logoutUser, login as loginUser
#from django.utils import timezone
from django.views.generic.base import View
from .models import CustomUser, Subscribers
#from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from django.core.mail import EmailMessage
from django.utils.encoding import force_bytes, force_text, DjangoUnicodeDecodeError
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.sites.shortcuts import get_current_site
from django.urls import reverse
from .utils import token_generator
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.hashers import check_password
from django.core.mail import EmailMultiAlternatives
from django.core.mail import EmailMultiAlternatives    
from django.http import HttpResponse
from django.template.loader import get_template
from django.contrib.auth.views import PasswordResetConfirmView

User = get_user_model()


# NECESSARY FUNCIONS FOR VIEWS

def index(request):
    return render(request, 'users/index.html', {})


def universityList(request):
    return render(request, 'users/universityList.html', {})




def profile(request):
    return render(request, 'users/profile.html', {})


def profileEdit(request):
    return render(request, 'users/profileEdit.html', {})

def sayfasifredegis(request):
    return render(request, 'users/password_change.html', {})


def passwordChangeDone(request):
    return render(request, 'users/password_change_done.html', {})

def kullanicisozlesmesi(request):
    return render(request, 'users/kullanicisozlesmesi.html', {})

def gizliliksozlesmesi(request):
    return render(request, 'users/gizliliksozlesmesi.html', {})

def funcsignupcompleted(request):
    return render(request, 'users/signupcompleted.html', {})

def subscribe(request):
    if request.method == 'POST':
        email = request.POST['email']
        if not email:
            return HttpResponseRedirect(reverse('users:index'))
        return HttpResponseRedirect(reverse(('users:aftersubsribe'), args=(email,)))

def aftersubsribe(request,email):
    subcriber = Subscribers.objects.get_or_create(email=email)
    return render(request, 'users/index.html', {'alert_message': 'Abone olduğunuz için teşekkür ederiz', 'alertColor': 'successfull'})



# NECESSARY FUNCIONS

def login(request):
    if request.method == 'POST':
        user = authenticate(
            username=request.POST['username'], password=request.POST['password'])


        if user is not None:
            # A backend authenticated the credentials
            loginUser(request, user)
            return render(request, 'users/index.html', {'alert_message': 'Başarılı', 'alertColor': 'successfull'})            
        else:
            user2 = User.objects.filter(username=request.POST['username'])
            if user2.count == 0:
                return render(request, 'users/index.html', {'alert_message': 'Kullanıcı Adı bulunamadı', 'alertColor': 'dangerr'})
            else:
                if not user2[0].is_active:
                    return render(request, 'users/index.html', {'alert_message': 'Lütfen Aktivasyon mailinden aktif hesabınızı aktif ediniz', 'alertColor': 'dangerr'})
                else:
                    return render(request, 'users/index.html', {'alert_message': 'Kullanıcı adınızla şifreniz uyuşmuyor, Lütfen Tekrar deneyin', 'alertColor': 'dangerr'})


def register(request):
    if request.method == 'POST':
        # try:
        if request.POST['password1'] == request.POST['password2']:
            username = request.POST['username']
            email = request.POST['email']
            password = request.POST['password1']
            user = CustomUser.objects.create_user(username, email, password)
            user.is_active = False
            user.save()
            uidb64 = urlsafe_base64_encode(force_bytes(user.pk))
            domain = get_current_site(request).domain
            link = reverse('users:activate', kwargs={
                           'uidb64': uidb64, 'token': token_generator.make_token(user)})
            activate_url = 'http://'+domain+link
            email_subject = "hesabınızı aktifleştirin"
            email_body = user.username + '   linke tıklayınız\n' + activate_url
            # emailsend = EmailMessage(
            #     email_subject,
            #     email_body,
            #     'portaluniversite@gmail.com',
            #     [user.email]
            # )
            # emailsend.send(fail_silently=False)

            # text = get_template('email_template.txt')
            # html = get_template('email_template.html')
            # data = {'templating variable': data_var}
            # # If Client cant receive html mails, it will receive the text
            # # only version. 
            # # Render the template with the data
            # content_txt = text.render(data)
            # content_html = html.render(data)

            # # Send mail
            # msg = EmailMultiAlternatives(email_subject, content_text, from_email, [to])
            # msg.attach_alternative(content_html, "text/html")
            # msg.send()


            subject, from_email, toperson = email_subject , 'portaluniversite@gmail.com', user.email
            text = get_template('users/signup_send_mail_txt.html')
            html = get_template('users/signup_send_mail_html.html')
            data = {'email_body': email_body ,'username': request.POST['username'] , 'activate_url':activate_url}
            text_content = text.render(data)
            html_content = html.render(data)
            msg = EmailMultiAlternatives(subject, text_content, from_email, [toperson])
            msg.attach_alternative(html_content, "text/html")
            msg.send()
            
            return render(request, 'users/index.html', {'alert_message': 'Başarılı, Adresinize Aktivasyon Maili gönderilmiştir', 'alertColor': 'successfull'})
        else:
            return render(request, 'users/index.html', {'alert_message': 'Şifreler Eşleşmedi', 'alertColor': 'dangerr'})
        # except:
        # return render(request, 'users/index.html', {'alert_message': 'Bir sorun ile karşılaşıldı', 'alertColor': 'danger'})
    else:
        return render(request, 'users/index.html', {'alert_message': 'Bir sorun ile karşılaşıldı', 'alertColor': 'dangerr'})


def logout(request):
    logoutUser(request)
    return render(request, 'users/index.html', {'alert_message': 'Başarılı', 'alertColor': 'successfull'})


def password_change(request):
    
    if request.method == 'POST':
        current_user = request.user
        if check_password(request.POST['password'], current_user.password):
            if request.POST['password1'] == request.POST['password2'] :
                current_user.set_password(request.POST['password1'])
                current_user.save()
                update_session_auth_hash(request, current_user)
                #return redirect('user:password_change_done')
                return redirect('users:password_change_done')
            else: return HttpResponse("Yeni Şifreler Eşleşmedi")
        else : return HttpResponse("Şifrenizi Hatalı Girdiniz")
    else: return HttpResponse("İlginç Bir Hata")


class VerificationView(View):
    def get(self, request, uidb64, token):
        try:

            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            #login(request, user)
            messages.success(request, ('hesabınız oluşturuldu'))
            return redirect('users:activated')
        else:
            messages.warning(
                request, ('doğrulama linki geçersiz, bir ihtimal daha önce kullanıldı'))
            return redirect('users:index')


def password_reset2(request):
    if request.method == 'POST':
        #PasswordResetConfirmView.get_user()
        current_user = request.user
        if request.POST['password1'] == request.POST['password2'] :
            current_user.set_password(request.POST['password1'])
            current_user.save()
            #update_session_auth_hash(request, current_user)
            return redirect('users:password_reset_complete')
        else: return HttpResponse("Yeni Şifreler Eşleşmedi")
    else: return HttpResponse("İlginç Bir Hata")

Apps/users/templates/users/blankpage.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Şifre Resetleme</title>
  <link rel="stylesheet" href="style.css">
  <style>
    * {
      margin: 0;
      padding: 0;
      /* box-sizing: border-box; } */
    }

    .container {
      background-color: rgb(213, 246, 213);
      width: 100%;
      min-height: 100%;
      position: absolute;
    }

    .kutu1 {
      background-color: rgb(179, 179, 241);
      height: 40em;
      max-width: 30em;
      margin: 5em auto;
    }

    h1 {
      padding-top: 1em;
      text-align: center;
    }

    input {
      border: .2em solid rgb(236, 198, 198);
      border-radius: .4em;
      /* margin-top: 1em; */
      /* margin-left: 2em; */
      padding: 0em 1em;
      width: 80%;
      margin: 1em auto;
      display: block;
    }

    input:focus {
      background-color: lightblue;
    }

    button {
      background-color: #4CAF50;
      border: none;
      color: white;
      padding: 16px 32px;
      text-decoration: none;
      /* margin: 4px 2px; */
      cursor: pointer;
      margin: auto;
      width: 80%;
      display: block;
    }
  </style>
</head>

<body>
  <div class="container">
    <div class="kutu1">
      <h1>Şifre Resetleme</h1>
      <form action="{% url 'users:password_reset2' %}" method="POST">
        {% csrf_token %}
        <input type="password" name="password1" id="password1" placeholder="yeni şifrenizi giriniz">
        <input type="password" name="password2" id="password2" placeholder="yeni şifrenizi giriniz">
        </br>
        <button type="submit">Onay</button>
      </form>
    </div>
  </div>
</body>

</html>

Apps/users/templates/users/eventDetail.html
{% extends "users/base.html" %}
{% static "" as baseUrl %}

{% block CustomStyle %}
<style>

</style>
{% endblock CustomStyle %}


{% block content %}


{% endblock content %}



{% block Customscript %}
<script>

</script>
{% endblock Customscript %}

Apps/users/templates/users/html_password_reset_email.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Şifre Sıfırlama Mail</title>
    <link rel="stylesheet" href="style.css">
    <style>
        * {
            margin: 0;
            padding: 0;
            /* box-sizing: border-box; } */
        }

        .container {
            background-color: rgb(213, 246, 213);
            width: 100%;
            min-height: 100%;
            position: absolute;
        }

        .kutu1 {
            background-color: rgb(179, 179, 241);
            height: 40em;
            max-width: 30em;
            margin: 5em auto;
        }
        p{
            text-align: center;
        }

        h1 {
            padding-top: 1em;
            text-align: center;
        }

        input {
            border: .2em solid rgb(236, 198, 198);
            border-radius: .4em;
            /* margin-top: 1em; */
            /* margin-left: 2em; */
            padding: 0em 1em;
            width: 80%;
            margin: 1em auto;
            display: block;
        }

        input:focus {
            background-color: lightblue;
        }

        a {
            font-weight: 800;
            background-color: #4CAF50;
            border: none;
            color: white;
            padding: 16px 32px;
            text-decoration: none;
            /* margin: 4px 2px; */
            cursor: pointer;
            margin: auto;
            width: 80%;
            display: block;
            text-align: center;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="kutu1">
            <h1>iyi günler </h1>
            </br>
            <p> kullanıcı adınız  :  {{ user.get_username }} </p>
            </br>
            <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}"> Yeni Şifre Al </a>
        </div>
    </div>
</body>

</html>

Apps/users/templates/users/index.html
{% extends "users/base.html" %}
{% block content %}
{% load static %}
<header class="masthead text-white text-center" style="background:url({%static 'assets/img/bg-masthead.jpg' %}) no-repeat center center; background-size:cover;">
    <div class="container">
        <div class="row no-gutters">
            <div class="col-xl-9 mx-auto">
                <h1 class="mb-5" style="font-family: Roboto, sans-serif;">Hayalinizdeki <br>üniversiteyi bulun</h1>
            </div>
            <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
                <form action="{% url 'universities:searchUniversity' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-row" data-bs-hover-animate="pulse">
                        <div class="col-12 col-md-9 col-xl-9 mb-2 mb-md-0"><input class="form-control form-control-lg" type="text" required name="searchText" placeholder="Üniversite Ara"></div>
                        <div class="col-12 col-md-3"><button class="btn btn-primary btn-block btn-lg" type="submit">Ara</button></div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</header>
<section class="features-icons bg-light text-center">
    <div class="container">
        <div class="row" style="margin: 0px -30px;">
            <div class="col">
                <h1 style="margin: 0 0 45px 0;">Üniversite neye göre seçilir?</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4">
                <div class="mx-auto features-icons-item mb-5 mb-lg-0 mb-lg-3">
                    <div class="d-flex features-icons-icon"><i class="fa fa-university m-auto text-primary" data-bs-hover-animate="pulse"></i></div>
                    <h3 style="font-family: Roboto, sans-serif;">Tür</h3>
                    <p class="lead mb-0" style="font-family: Roboto, sans-serif;">Devlet Üniversitesi mi<br>Yoksa Özel Üniversite mi ?</p>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="mx-auto features-icons-item mb-5 mb-lg-0 mb-lg-3">
                    <div class="d-flex features-icons-icon"><i class="icon-plane m-auto text-primary" data-bs-hover-animate="pulse"></i></div>
                    <h3 style="font-family: Roboto, sans-serif;">Ulaşım</h3>
                    <p class="lead mb-0" style="font-family: Roboto, sans-serif;">Bulunduğu şehir önemli mi?</p>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="mx-auto features-icons-item mb-5 mb-lg-0 mb-lg-3">
                    <div class="d-flex features-icons-icon"><i class="fa fa-sort-amount-asc m-auto text-primary" data-bs-hover-animate="pulse"></i></div>
                    <h3 style="font-family: Roboto, sans-serif;">Sıralama</h3>
                    <p class="lead mb-0" style="font-family: Roboto, sans-serif;">En iyi üniversite en yüksek<br>puanda olan mı?</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="showcase">
    <div class="container-fluid p-0">
        <div class="row no-gutters">
            <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background: url({% static 'assets/img/1.jpg' %}) center / contain no-repeat;"><span></span></div>
            <div class="col-lg-5 my-auto order-lg-1 showcase-text ml-5">
                <h2>İş İmkanları</h2>
                <p class="lead mb-0">İş imkanları üniversiteden mezun olduktan sonra en gerekli faktörlerden birisidir. Mezun olduktan sonra iş imkanlarına göre işe girmek gerekir. Bir üniversite seçerken, öncelikle o üniversitenin mezunlarının iş bulup bulamadığına bakmak
                    akıllıca olabilir.</p>
            </div>
        </div>
        <div class="row no-gutters">
            <div class="col-lg-6 text-white showcase-img" style="background: url({% static 'assets/img/2.jpeg'%}) center / contain no-repeat;"><span></span></div>
            <div class="col-lg-6 my-auto order-lg-1 showcase-text">
                <h2>Kazanılan bilgiler</h2>
                <p class="lead mb-0">Üniversitelerin bir çoğunda çok değerli bilgiler elde etmek mümkünken, bazı kesimlerimde eğitim şartlarından ve profesörlerin kalite farkından dolayı farklılıklar olabiliyor.</p>
            </div>
        </div>
        <div class="row no-gutters">
            <!-- @ts-ignore -->
            <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background: url({% static 'assets/img/3.jpg' %}) center / auto no-repeat;"><span></span></div>
            <div class="col-lg-5 my-auto order-lg-1 showcase-text ml-5">
                <h2>Yurtdışı imkanları</h2>
                <p class="lead mb-0">Üniversiteleri seçerken yurtdışı imkanlarına da dikkat ederek bir üniversite seçmek ileride çok büyük farklara yol açabilmektedir.</p>
            </div>
        </div>
    </div>
</section>
<section class="testimonials text-center bg-light">
    <div class="container">
        <h2 class="mb-5">Rehber Yazılarında İnsanlar Neler Diyor</h2>
        <div class="row">
            <div class="col-lg-4">
                <div class="mx-auto testimonial-item mb-5 mb-lg-0"><img class="rounded-circle img-fluid mb-3" src="{% static 'assets/img/testimonials-1.jpg'%}">
                    <h5>Ayşe H.</h5>
                    <p class="font-weight-light mb-0" style="font-family: Roboto, sans-serif;">Devlet üniversitesinin önemi<br>anlatmakla bitmez.</p>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="mx-auto testimonial-item mb-5 mb-lg-0"><img class="rounded-circle img-fluid mb-3" src="{% static 'assets/img/testimonials-2.jpg'%}">
                    <h5>Mehmet B.</h5>
                    <p class="font-weight-light mb-0" style="font-family: Roboto, sans-serif;">En önemli şey Üniversitenin<br>insanlar tarafından bakış açısı.</p>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="mx-auto testimonial-item mb-5 mb-lg-0"><img class="rounded-circle img-fluid mb-3" src="{% static 'assets/img/testimonials-3.jpg'%}">
                    <h5>Fatma S.</h5>
                    <p class="font-weight-light mb-0">Yurtdışı herşey demektir.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="call-to-action text-white text-center" style="background:url({%static 'assets/img/bg-masthead.jpg'%}) no-repeat center center;background-size:cover;">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-xl-9 mx-auto">
                <h2 class="mb-4">Yeni güncellemelerden haberdar olmak için<br>mail aderesinizi giriniz</h2>
            </div>
            <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
                <form action="{% url 'users:subscribe' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-12 col-md-9 mb-2 mb-md-0"><input class="form-control form-control-lg" required type="email" name="email" placeholder="Mail adresinizi giriniz"></div>
                        <div class="col-12 col-md-3"><button class="btn btn-primary btn-block btn-lg" type="submit">Kayıt Ol</button></div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

{% block Customscript %}
<script>
    
    // Script for the search functionality 
    $("form").submit(function () {
        var input = $("<input>").attr("name", "city").val('cityNull');
        $(this).append(input);
        return true;
    });
</script>
{% endblock Customscript %}

Apps/users/templates/users/password_change.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Şifre Değiştirme</title>
  <link rel="stylesheet" href="style.css">
  <style>
    * {
      margin: 0;
      padding: 0;
      /* box-sizing: border-box; } */
    }

    .container {
      background-color: rgb(213, 246, 213);
      width: 100%;
      min-height: 100%;
      position: absolute;
    }

    .kutu1 {
      background-color: rgb(179, 179, 241);
      height: 40em;
      max-width: 30em;
      margin: 5em auto;
    }

    h1 {
      padding-top: 1em;
      text-align: center;
    }

    input {
      border: .2em solid rgb(236, 198, 198);
      border-radius: .4em;
      /* margin-top: 1em; */
      /* margin-left: 2em; */
      padding: 0em 1em;
      width: 80%;
      margin: 1em auto;
      display: block;
    }

    input:focus {
      background-color: lightblue;
    }

    button {
      background-color: #4CAF50;
      border: none;
      color: white;
      padding: 16px 32px;
      text-decoration: none;
      /* margin: 4px 2px; */
      cursor: pointer;
      margin: auto;
      width: 80%;
      display: block;
    }
  </style>
</head>

<body>
  <div class="container">
    <div class="kutu1">
      <h1>Şifre Değiştirme</h1>
      <form action="{% url 'users:password_change2' %}" method="POST">
        {% csrf_token %}
        <input type="password" name="password" id="password" placeholder="şifrenizi giriniz">
        <input type="password" name="password1" id="password1" placeholder="yeni şifre">
        <input type="password" name="password2" id="password2" placeholder="yeni şifre">
        </br>
        <button type="submit">Onay</button>
      </form>
    </div>
  </div>
</body>

</html>

Apps/users/templates/users/password_change_done.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Şifre Değiştirildi</title>
  <link rel="stylesheet" href="style.css">
  <style>
    * {
      margin: 0;
      padding: 0;
      /* box-sizing: border-box; } */
    }

    .container {
      background-color: rgb(213, 246, 213);
      width: 100%;
      min-height: 100%;
      position: absolute;
    }

    .kutu1 {
      background-color: rgb(179, 179, 241);
      height: 40em;
      max-width: 30em;
      margin: 5em auto;
    }

    h1 {
      padding-top: 1em;
      text-align: center;
    }

    input {
      border: .2em solid rgb(236, 198, 198);
      border-radius: .4em;
      /* margin-top: 1em; */
      /* margin-left: 2em; */
      padding: 0em 1em;
      width: 80%;
      margin: 1em auto;
      display: block;
    }

    input:focus {
      background-color: lightblue;
    }

    a {
      background-color: #4CAF50;
      border: none;
      color: white;
      padding: 16px 32px;
      text-decoration: none;
      /* margin: 4px 2px; */
      cursor: pointer;
      margin: auto;
      width: 80%;
      display: block;
      text-align: center;
    }
  </style>
</head>

<body>
  <div class="container">
    <div class="kutu1">
      <h1>Şifreniz Değiştirildi</h1>
       </br>
        <a href="{% url 'users:index' %}">Anasayfaya Dön</a>
    </div>
  </div>
</body>

</html>

Apps/users/templates/users/password_reset_email.html
iyi günler 

kullanıcı adınız : {{ user.get_username }}

şifrenizi sınıflamak için linke gidiniz ;

{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

Apps/users/templates/users/profileEdit.html
profileEDit

Apps/users/templates/users/signup_send_mail_txt.html
{{email_body}}