Apps/comments/urls.py
from django.urls import path

from . import views

app_name = 'comments'
urlpatterns = [
    path('', views.index, name='index'),
    path('createpost/', views.createpost, name='createpost'),
    path('deletepost/<int:post_id>', views.deletepost, name='deletepost'),
    path('editpost/', views.editpost, name='editpost'),
]

University/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('comments/', include('Apps.comments.urls')),
    path('universities/', include('Apps.universities.urls')),
    path('', include('Apps.users.urls')),
    path('apptercih/',include('Apps.apptercih.urls')),
    path('calendar/',include('Apps.calendars.urls')),
    path('blogs/',include('Apps.blogs.urls')),
    path('tercihrobotu/',include('Apps.apptercihrobotu.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Apps/comments/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class Post(models.Model):
    text = models.CharField(max_length=200)
    created_time = models.DateTimeField('date published')
    is_edited = models.BooleanField(default=False)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    likes = models.IntegerField(default=0)

    def __str__(self):
        return self.text

Apps/comments/views.py
from django.shortcuts import get_object_or_404, render
from .models import Post
from django.utils import timezone
from django.http import JsonResponse
# Create your views here.

def index(request):
    return render(request, 'comments/index.html', {'postList': Post.objects.order_by('-created_time')[:20]})


def createpost(request):
    if request.method == 'POST':
        textField = request.POST['textField']
        created_time = timezone.now()
        is_edited = False
        likes = 0
        newPost = Post(text=textField, created_time=created_time, is_edited=is_edited, likes=likes, owner=request.user)
        newPost.save()
        return render(request, 'comments/index.html', {'postList': Post.objects.order_by('-created_time')[:20], 'alert_message': 'Başarılı', 'alertColor': 'successfull'})
    return render(request, 'comments/index.html', {'postList': Post.objects.order_by('-created_time')[:20], 'alert_message': 'Yeni Bir Blog Oluşturulamadı Lütfen Tekrar deneyin', 'alertColor': 'dangerr'})
    
    
def deletepost(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if(post.owner.id == request.user.id):
        try:
            postText = post.text
            post.delete()
            return render(request, 'comments/index.html', {'postList': Post.objects.order_by('-created_time')[:20], 'alert_message': 'Başarılı', 'alertColor': 'successfull'})
        except:
            return render(request, 'comments/index.html', {'postList': Post.objects.order_by('-created_time')[:20], 'alert_message': 'Bloğunuz silinemedi Lütfen Tekrar deneyin', 'alertColor': 'dangerr'})
    else:
        return render(request, 'comments/index.html', {'postList': Post.objects.order_by('-created_time')[:20], 'alert_message': 'Sadece kendi blogunuzu silebilirsiniz', 'alertColor': 'dangerr'})


def editpost(request):
    # request should be ajax and method should be POST.
    if request.is_ajax and request.method == "POST":
        dataList = request.body.decode('utf-8').split('&')
        post_id= 0
        post_text= ""
        for item in dataList:
            value = item.split('=')
            if(value[0] == 'post_id'):
                post_id = value[1]
            elif(value[0] == 'post_text'):
                post_text = value[1]
            else:
                continue

        post = get_object_or_404(Post, pk=post_id)
        if(post.owner.id == request.user.id):
            post.text = post_text
            post.save()
            return JsonResponse({'alert_message': 'Başarılı', 'alertColor': 'successfull'}, status = 200)
        else:
            return JsonResponse({'alert_message': 'Sizin bu blogu silmeye yetkiniz yok', 'alertColor': 'dangerr'}, status = 400)

    return JsonResponse({'alert_message': 'Bir hata ile karşılaşıldı', 'alertColor': 'dangerr'}, status = 400)







    

Apps/comments/templates/comments/index.html
{% block comments %}


<div class="container-fluid mb-5">
    <div class="row justify-content-center">
        <div class="col-10">

            <form class="mt-5" action="{% url 'comments:createpost' %}" method="POST">
                {% csrf_token %}
                <div>
                    <label for="textField">Düşüncelerinizi Paylaşın</label>
                    <textarea class="form-control" name="textField" id="textField" {% if not user.is_authenticated %} disabled  {% endif %} placeholder="Ne düşünüyorsun? Düşüncelerini Paylaş" required></textarea>
                </div>
                <div class="float-right mt-2">
                    <button type="submit" class="btn btn-primary ">Submit</button>
                </div>
            </form>

            <h3 class="mx-auto my-5">Recent Posts</h3>
            <div class="w-100"></div>
                {% for o in postList %}
                    <div class="card mt-3">
                        <div class="card-body">
                            {% if user == o.owner %}
                                <!-- <a href="{% url 'comments:deletepost' o.id %}" class="btn ml-2 mb-1 close" aria-label="Close"><span aria-hidden="true">&times;</span></a> -->
                                <div class="btn-group dropright" data-bs-hover-animate="pulse" style="position: absolute; right: 0px; width: 3%; margin-top: -20px;">
                                    <a class="btn" data-toggle="dropdown" data-display="static" aria-haspopup="true" aria-expanded="true"><i class="fa fa-navicon" style="font-size: 20px; color:grey"></i></a>
                                    <div class="dropdown-menu dropdown-menu-lg-right">
                                        <!-- <a class="dropdown-item" data-toggle="modal" data-target="#editPost" data-id="{{o.id}}" data-text="{{o.text}}" data-id="{{o.owner}}">Düzenle</a> -->
                                        <a class="dropdown-item" id="btnPost_{{o.id}}" href="javascript:openModal('{{o.id}}','{{o.text}}','{{o.owner}}');">Düzenle</a>
                                        <a href="{% url 'comments:deletepost' o.id %}" class="dropdown-item">Sil</a>
                                    </div>
                                </div>
                            {% endif %}    
                            <blockquote class="blockquote mb-0">
                              <p id=post_{{o.id}}>{{o.text}}</p>
                            </blockquote>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">- {{o.owner}}</small>
                            <small class="text-muted"> {{o.created_time}}</small>
                        </div>
                    </div>
                {% endfor %}
        </div>
    </div>
</div>

<div class="modal fade" id="editPost" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Yorum Düzenleme</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Sahibi: </label>
                        <input type="text" class="form-control" id="post_owner" disabled>
                        </div>
                        <div class="form-group">
                        <label for="message-text" class="col-form-label">Yazı: </label>
                        <textarea class="form-control" id="post_text"></textarea>
                        </div>
                        <!-- <input type="text" class="form-control" id="post_id" disabled style="visibility:hidden"> -->
                    </div>
                </form>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">İptal</button>
                <button id="saveChanges" type="submit" class="btn btn-primary">Kaydet</button>
            </div>
      </div>
    </div>
  </div>


{% endblock comments %}


{% block Customscript %}

    <script>

        var lastPostId = 0;
        var lastPostText = 0;
        var ownerId = 0;

        function openModal(post_id, post_text, post_owner) {
            $('#editPost').modal();
            $('#editPost').trigger('focus');
            $('#post_text').val(post_text);
            $('#post_owner').val(post_owner);
            lastPostId = post_id;
            lastPostText = post_text;
            ownerId = post_owner;
        }

        $("#saveChanges").click(function (e) {

            var currentText = $('#post_text').first().val();
            if(lastPostText != currentText){
                // preventing from page reload and default actions

                $.ajax({
                    type: 'POST',
                    url: "{% url 'comments:editpost' %}",
                    data: {
                        post_id: lastPostId,
                        post_text: currentText,
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                    },

                    success: function (response) {
                        $('#post_' + lastPostId).text(currentText);
                        $('#post_' + lastPostId).trigger('focus');
                        $('#editPost').modal('toggle');

                        var btnProperties = document.getElementById('btnPost_' + lastPostId);
                        btnProperties.setAttribute('href', "javascript:openModal('" + lastPostId + "','"  + currentText + "','" + ownerId + "');");
                        var x = document.getElementById("snackbar1");
                        x.className = "show makegreen";
                        text = response['alert_message'];
                        x.innerHTML = "<b>"+ text +"</b>"
                        setTimeout(function(){ x.className = x.className.replace("show makegreen", "makegreen"); }, 3000);
                    },
                    error: function (response) {
                        var x = document.getElementById("snackbar1");
                        x.className = "show makered";
                        text = response['alert_message'];
                        x.innerHTML = "<b>"+ text +"</b>"
                        setTimeout(function(){ x.className = x.className.replace("show makered", "makered"); }, 3000);
                    }
                })
            }
        })
    </script>
{% endblock Customscript %}